[manifest]
version = "1.0.0"
dump_lua = true
priority = 2147483600

[[patches]]
[patches.regex]
target = "card.lua"
pattern = '''\) then self.cost = 0 end'''
position = 'after'
payload = '''if self.edition and self.edition.type == 'mp_phantom' then self.sell_cost = 0 end'''
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if G.jokers.cards[i] ~= self then'''
position = 'at'
payload = '''if G.jokers.cards[i] ~= self and (not G.jokers.cards[i].edition or G.jokers.cards[i].edition.type ~= "mp_phantom") then'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''local chosen_joker = pseudorandom_element(G.jokers.cards, pseudoseed('ankh_choice'))'''
position = 'at'
payload = '''local copyable_jokers = {}
    for i, v in ipairs(G.jokers.cards) do
      if not G.jokers.cards[i].edition or G.jokers.cards[i].edition.type ~= "mp_phantom" then copyable_jokers[#copyable_jokers + 1] = v end
    end
    local chosen_joker = pseudorandom_element(copyable_jokers, pseudoseed('ankh_choice'))'''
match_indent = true
times = 1

[[patches]]
[patches.regex]
target = "card.lua"
pattern = '''--if there is at least one joker(?<pre>[\s\S]+?)for k, v in pairs\(G.jokers.cards\) do'''
position = 'at'
payload = '''--if there is at least one joker$pre local copyable_jokers = {}
      for i, v in ipairs(G.jokers.cards) do
        if not G.jokers.cards[i].edition or G.jokers.cards[i].edition.type ~= "mp_phantom" then copyable_jokers[#copyable_jokers + 1] = v end
      end
      for k, v in pairs(copyable_jokers) do'''
times = 1

# Sets the balanced sticker on reworked cards
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if center.consumeable then'''
position = 'before'
payload = '''
if old_center ~= center or initial then
	if MP.LOBBY.config.ruleset then
		local ruleset = string.sub(MP.LOBBY.config.ruleset, 12, #MP.LOBBY.config.ruleset)
		
		if center.mp_reworks and center.mp_reworks[ruleset] and ruleset ~= 'vanilla' then
			if not center.mp_silent[ruleset] then
				self.ability.mp_sticker_balanced = true
			end
		end
	end
end'''
match_indent = true
times = 1

# Fixes the issue with baseball card working on phantom jokers
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Baseball Card' and (context.other_joker.config.center.rarity == 2 or context.other_joker.config.center.rarity == "Uncommon") and self ~= context.other_joker then'''
position = 'after'
payload = '''if context.other_joker.edition and context.other_joker.edition.type == 'mp_phantom' then return end'''
match_indent = true
times = 1

# align sixth sense trigger behaviour with vanilla - STEAMODDED BUG
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if self.ability.name == 'Sixth Sense' and #context.full_hand == 1 and context.full_hand[1]:get_id() == 6 and G.GAME.current_round.hands_played == 0 then'''
position = 'after'
payload = '''if ( SMODS.find_card('j_sixth_sense') )[1] ~= self then return end'''
match_indent = true
times = 1