[manifest]
version = "1.0.0"
dump_lua = true
priority = 2147483600

[[patches]]
[patches.pattern]
target = '''functions/UI_definitions.lua'''
pattern = "if v.pinned then card.pinned = true end"
position = 'after'
payload = "if v.rental then card:set_rental(true) end"
match_indent = true

[[patches]]
[patches.pattern]
target = '''game.lua'''
pattern = "if v.pinned then _joker.pinned = true end"
position = 'after'
payload = "if v.rental then _joker:set_rental(true) end"
match_indent = true
